### ISSUE TITLE
Value "\" must be a URL path, and start with a "/"

### ISSUE THREAD

**Issue by mashirooooo** [karolis-sh/electron-snowpack#16]
Run on window system, I Got an error
node: 12.16.1
window10
error:
Value "\" must be a URL path, and start with a "/"
[electron-snowpack] �🚨 An unexpected error has occurred!

It seems that the first line of `electron-snowpack\config\snowpack.js` is modified to `const path = require('path').posix;`
that can fix it
I don't know if there are other problems

**Comment by mashirooooo** [comment]
There was another problem when I run `yarn build`, so i change ` mount: {
    public: { url: path.posix.join('/', config.baseHref), static: true },
    'src/renderer': path.posix.join('/', config.rendererBaseHref),
  },`  replace `const path = require('path').posix;`

**Comment by mashirooooo** [comment]
The last question, is there any plan to provide a vue3 template.

**Comment by karolis-sh** [comment]
Could you run with `--verbose` mode and provide the output? I haven't touched Windows dev environments in ages, this would help me to get what's happening different on Unix systems.

Rergards vue - sure I'll add that later.

**Comment by karolis-sh** [comment]
For now, you can probably surpass the error with, a hardcoded `snopack.cofnig.js` value:

```js
{
  mount: {
    public: {url: '/', static: true},
    src: {url: '/dist'},
  },
}
```

**Comment by mashirooooo** [comment]
when i  change `snopack.cofnig.js` and run `yarn dev --verbose ` 
the output is 
`
[snowpack] loaded plugin: C:\Users\Administrator\Desktop\hello-world\node_modules\@snowpack\plugin-dotenv\plugin.js
[electron-snowpack] Starting Snowpack server with config: {
  "root": "C:\\Users\\Administrator\\Desktop\\hello-world",
  "plugins": [
    {
      "name": "@snowpack/plugin-dotenv"
    },
    {
      "name": "@snowpack/plugin-esbuild",
      "resolve": {
        "input": [
          ".mjs",
          ".jsx",
          ".ts",
          ".tsx"
        ],
        "output": [
          ".js"
        ]
      }
    }
  ],
  "alias": {},
  "exclude": [
    "**/node_modules/**/*",
    "C:\\Users\\Administrator\\Desktop\\hello-world\\dist\\renderer/**/*"
  ],
  "routes": [],
  "devOptions": {
    "secure": false,
    "hostname": "localhost",
    "port": 9510,
    "open": "none",
    "output": "stream",
    "hmrDelay": 0,
    "hmrErrorOverlay": true
  },
  "buildOptions": {
    "out": "C:\\Users\\Administrator\\Desktop\\hello-world\\dist\\renderer",
    "baseUrl": "/",
    "metaUrlPath": "/_snowpack",
    "clean": true,
    "sourcemap": false,
    "watch": false,
    "htmlFragments": false,
    "ssr": false
  },
  "testOptions": {
    "files": [
      "__tests__/**/*",
      "**/*.@(spec|test).*"
    ]
  },
  "packageOptions": {
    "source": "local",
    "external": [
      "assert",
      "async_hooks",
      "buffer",
      "child_process",
      "cluster",
      "console",
      "constants",
      "crypto",
      "dgram",
      "dns",
      "domain",
      "events",
      "fs",
      "http",
      "http2",
      "https",
      "inspector",
      "module",
      "net",
      "os",
      "path",
      "perf_hooks",
      "punycode",
      "querystring",
      "readline",
      "repl",
      "stream",
      "string_decoder",
      "timers",
      "tls",
      "trace_events",
      "tty",
      "url",
      "util",
      "v8",
      "vm",
      "worker_threads",
      "zlib",
      "electron"
    ],
    "packageLookupFields": [],
    "knownEntrypoints": [],
    "rollup": {
      "plugins": []
    }
  },
  "mount": {
    "C:\\Users\\Administrator\\Desktop\\hello-world\\public": {
      "url": "/",
      "static": true,
      "resolve": true
    },
    "C:\\Users\\Administrator\\Desktop\\hello-world\\src\\renderer": {
      "url": "/dist",
      "static": false,
      "resolve": true
    }
  },
  "extends": "electron-snowpack/config/snowpack.js",
  "_extensionMap": {
    ".mjs": [
      ".js"
    ],
    ".jsx": [
      ".js"
    ],
    ".ts": [
      ".js"
    ],
    ".tsx": [
      ".js"
    ]
  }
}
[electron-snowpack] Starting esbuild build with config: {
  "platform": "node",
  "format": "cjs",
  "entryPoints": [
    "src/main/index.js"
  ],
  "outdir": "dist\\main",
  "define": {
    "process.env.NODE_ENV": "\"development\"",
    "process.env.MODE": "\"development\"",
    "process.env.SNOWPACK_PORT": "\"9510\"",
    "process.env.SNOWPACK_PUBLIC_BASE_HREF": "\".\"",
    "process.env.SNOWPACK_PUBLIC_RENDERER_BASE_HREF": "\"dist\""
  },
  "logLevel": "info"
}
[snowpack] Using in-memory cache.
[snowpack] Mounting directories:
[snowpack]  -> 'C:\Users\Administrator\Desktop\hello-world\public' as URL '/'
[snowpack]  -> 'C:\Users\Administrator\Desktop\hello-world\src\renderer' as URL '/dist'
[snowpack] Using cache folder: node_modules\.cache\snowpack\development
[snowpack] Cache out of date or missing. Updating...
[snowpack] Skip scanning public\electron-snowpack.svg for imports (unknown file extension .svg)
[snowpack] Scanning public\index.html for imports as HTML
[snowpack] Scanning src\renderer\common\lang.min.js for imports as JS
[snowpack] Scanning src\renderer\common\quasar.umd.js for imports as JS
[snowpack] Scanning src\renderer\common\svg.min.js for imports as JS
[snowpack] Scanning src\renderer\index.css for imports as CSS
[snowpack] Scanning src\renderer\index.js for imports as JS
[snowpack] Scanning src\renderer\style\font_icon.css for imports as CSS
[snowpack] Scanning src\renderer\style\quasar.css for imports as CSS
[snowpack] Nothing to install.
  http://localhost:9510 • http://10.0.200.79:9510
  Server started in 76ms.


[electron-snowpack] Starting an electron process with arguments: ["dist\\main\\index.js"]
[electron]

[electron] (node:12764) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

[snowpack] [200] GET /index.html
[snowpack] [200] GET /_snowpack/hmr-client.js
[snowpack] [200] GET /_snowpack/hmr-error-overlay.js
[snowpack] [200] GET /electron-snowpack.svg
[snowpack] [200] GET /dist/index.css
[snowpack] [200] GET /dist/index.js
[snowpack] optimized etag! sending 304...
[snowpack] [304] GET /dist/index.css`

**Comment by karolis-sh** [comment]
Issues should be fixed, try the latest version. Also added the vue example.
