### ISSUE TITLE
Add support for a shared folder

### ISSUE THREAD

**Issue by BarFoo** [karolis-sh/electron-snowpack#20]
Hello,

First of all thank you for your fantastic work on this. It has helped me save time immensely.

I'd like to request adding support for a shared folder. Especially when Typescript is also supported for src/main in the future.

One use case for this is for interfaces that can be shared between main and renderer.

Consider the following interface:

``
export interface Something {
   somethingA: string;
   somethingB: number;
}
``

Then in the main process we have an IPC handle:

``
ipcMain.handle("my-channel", (event, args) => {
   // Return something or do something
});
``

And in the renderer:

``
ipcRenderer.invoke("my-channel", something);
``

Likewise for common services that could be shared between main and renderer.

Thanks

**Comment by karolis-sh** [comment]
Glad this helped not only me 😃

I was thinking about a shared folder, I will look into that **after** typescript support for `main`. Though it has some fundamental inconsistencies as both main and renderer would bundle it and you can't really be sure that both processes will get the same result. For now, I'd suggest creating a yarn workspace with your constants and re-use them in both main and renderer.

**Comment by BarFoo** [comment]
Hi,

Thanks for getting back to me. I look forward to the updates, if I can help out in anyway let me know!

Thanks

**Comment by karolis-sh** [comment]
@BarFoo upgrade to latest version and check examples for setup config

**Comment by BarFoo** [comment]
@karolis-sh Thanks very much, I will check it out.
