### ISSUE TITLE
Preload script and forked scripts do not work in production

### ISSUE THREAD

**Issue by BarFoo** [karolis-sh/electron-snowpack#27]
When creating a BrowserWindow with a preload script, which exposes electron via a context bridge, this preload script is not bundled to dist/main, so in production it can't be found.

Minimal example of code:

```
window = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      enableRemoteModule: false,
      preload: path.join(__dirname, "preload.js"), < PROBLEM
    },
});
```

This is also the same for any scripts loaded with fork.

How can I include these additional scripts into the output for main?

**Comment by BarFoo** [comment]
I've come up with a nice solution for my needs in the mean time. I have named any preload script or similar as `[name].script.js` and I've setup the following in package.json:

```
"scripts": {
    "build": "electron-snowpack build && copyfiles -f src/**/*.script.js dist/main"
}
```

This copies preload.script.js and any others with the same ending to dist/main, that then get included into the bundled ASAR.

Then the forked scripts (called with fork) and preload are now working as expected after bundling the app.

Thanks

**Comment by karolis-sh** [comment]
As you've found out, since the `preload.js` is just a standalone script (separate from Snowpack bundling process), you would need to transfer it to the `dist` directory for a production build.
