### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by IceSentry** [karolis-sh/electron-snowpack#37]
- You might want to use a less restrictive peerDep on `electron`. Curremtly it's only looking for electron 11, but I don't see anything in this lib that actually requires any specific version of electron.
- in `getAssetUrl` you are using `url.format` which is deprecated in node v15. I know that electron uses a slightly older version, but switching to using the default URL constructor is the recommended fix. Personally I replaced `url.format` with `new URL(``file:///${path.join(__dirname, asset)}``).href`

**Comment by karolis-sh** [comment]
good points, updated
