### ISSUE TITLE
Examples have missing npm-run-all dev dependency

### ISSUE THREAD

**Issue by bgever** [karolis-sh/electron-snowpack#43]
When I tried to run the `try` script in the examples (no pun intended), npm complained it didn't know the `run-s` command.

Installing the `npm-run-all` package as a dev dependency solved it for me. Is this package maybe installed globally on your machine @karolis-sh?

**Comment by karolis-sh** [comment]
It's installed via the monorepo root [pakcage.json](https://github.com/karolis-sh/electron-snowpack/blob/main/package.json#L65) file, but I guess it would make sense to also add that dependency to every example to have a more complete structure.

**Comment by bgever** [comment]
I see. I was expecting the example folders can be used in isolation, since I'm trying to make a Preact project based off them. Would be great indeed to add the dependencies to the example package.json files.

**Comment by bgever** [comment]
Thanks for the updates @karolis-sh!

**Comment by karolis-sh** [comment]
Cheers! 🤝
