### ISSUE TITLE
I get empty windows for the examples built with electron-builder on Windows 10

### ISSUE THREAD

**Issue by giohappy** [karolis-sh/electron-snowpack#64]
I was testing the examples. They work perfectly in dev but when I try the  .exe (created with npm run dist) I alwasy get an empty HTML and the devtools open up automatically as in dev mode, as if the `process.env.MODE` wasn't set to "production".

- NodeJS 17.8.0
- npm 8.5.5
- Windows 10

**Comment by giohappy** [comment]
My fault. Right after writing the issue I thought that I should have run the `npm run build` command to prepare the production files, before creating the distribution.

What about prepending the dist script with build?

`"dist": "run-s clean build electron-builder",`

**Comment by karolis-sh** [comment]
Well, these are just example commands for reference. Personally, I'd add like a separate `release` or something similar for an actual project.

**Comment by giohappy** [comment]
sure @karolis-sh. Thanks so much for this template repo and the examples, they're very useful to bootstrap a project.

**Comment by karolis-sh** [comment]
Cheers! Glad this helped
