### ISSUE TITLE
Set sourcemap option in dev esbuild configuration

### ISSUE THREAD

**Issue by giohappy** [karolis-sh/electron-snowpack#65]
I was struggling with VSCode debuggin of the main process. Finally I've discovered that all that was needed was configuring the sourcemap [inside the esbuild configuration](https://github.com/karolis-sh/electron-snowpack/blob/main/packages/electron-snowpack/lib/get-esbuild-config.js#L30).

I've added `sourcemap = 'inline'` to the options parameter for  `getESBuildConfig` inside [the dev command](https://github.com/karolis-sh/electron-snowpack/blob/main/packages/electron-snowpack/lib/command/dev.js#L50) and it worked like a charm.

**Comment by karolis-sh** [comment]
Wouldn't it work with `true` (`linked`, https://esbuild.github.io/api/#sourcemap)? I think inline might not be that efficient 🤔

**Comment by giohappy** [comment]
I haven't tried `true` but it should work too and I agree it would probably be more efficient.

**Comment by karolis-sh** [comment]
Released in `0.13.0`
